export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const CURRENT_USER_FETCHED = "CURRENT_USER_FETCHED";

export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const ADD_MESSAGE = "ADD_MESSAGE";

export const GET_USER = "GET_USER";
export const USER_FETCHED = "USER_FETCHED";
export const SHOW_USERS = "SHOW_USERS";

export const SET_CHANNEL = "SET_CHANNEL";
export const ADD_CHANNEL = "ADD_CHANNEL";
export const CHANNELS_FETCHED = "CHANNELS_FETCHED";
export const GET_CHANNELS = "GET_CHANNELS";
export const GET_CHANNEL = "GET_CHANNEL";
